#!/bin/bash

source "$(git --exec-path)/git-sh-setup"

USAGE="[major|minor|patch|version]"

function _publish() {
    if [[ $# == 1 ]]; then
        VPATTERN='^[0-9]+\.[0-9]+\.[0-9]+$'
        if [[ $1 =~ $VPATTERN ]]; then
            BRANCH="$(git rev-parse --abbrev-ref HEAD)"
            if [[ "$BRANCH" != "master" && "$BRANCH" != "main"  ]]; then
                echo 'Can only publish from master or main branch';
                exit 1;
            fi
            VERSION=$1
            git commit -am "v${VERSION} Pre-Release"
            git push origin $BRANCH
            git tag -a v${VERSION} -m "Version ${VERSION}"
            git push origin v$VERSION
        elif [[ $1 == 'major' || $1 == 'minor' || $1 == 'patch' ]]; then
            die "$1 not currently supported"
        else
            die "$1 is an invalid version number"
        fi
    else
        usage
    fi
}

_publish $1
